WAI-16 - Реализовать логику авторизации
DinaEll/waika_project pull request #12
Opened 2024-08-29 21:46 UTC by sergeyemelianov

### Какую задачу решаем
Реализовать логику авторизации

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-08-30 05:36 UTC, goodprofy requested changes
Поправь тип и nav пожалуйста.

2024-08-30 05:36 UTC, goodprofy commented on packages/client/src/pages/LoginPage/ui/LoginPage.tsx
>    const handleSubmit = (values: signInRequest): void => {
Поправь тип signInRequest пожалуйста. С большой буквы, в прошлый раз пропустили.

2024-08-31 10:11 UTC, legeidaa approved these changes

2024-09-01 14:09 UTC, goodprofy approved these changes

2024-09-02 06:19 UTC, kyzinatra commented on packages/client/src/pages/LoginPage/ui/LoginPage.tsx
> +        'Content-Type': 'application/json; charset=UTF-8',
Можно лучше: стоит вынести логику запросов в отдельную абстракцию. Для этого рекомендую этот ролик. Он не очень простой, но подходы, которые там описываются мастхев для средних и больших проектов 

https://youtu.be/WMO9aarO390?si=jwXVgTqqaPCwoMsL

2024-09-02 06:20 UTC, kyzinatra commented on packages/client/src/pages/LoginPage/ui/LoginPage.tsx
> +      .catch(error => console.error(error))
Также стоит добавить обработку ошибок с выводом информации для пользователя, так как обычные юзеры не смотрят в консоль

2024-09-02 06:20 UTC, kyzinatra commented on packages/client/src/pages/RegistrationPage/ui/RegistrationPage.tsx
> +
Также константы также стоит вынести отдельно

2024-09-02 06:28 UTC, kyzinatra requested changes
Отличная работа! Вы отлично потрудились, но сейчас есть небольшие вопросы к реализации запросов. Много логики повторяется, выглядит довольно громоздко. Стоит поправить этот момент и ваша работа будет принята!

2024-09-02 07:03 UTC, sergeyemelianov commented on packages/client/src/pages/LoginPage/ui/LoginPage.tsx
> +        'Content-Type': 'application/json; charset=UTF-8',
По договоренности с командой запросы не выносили в общую логику

2024-09-02 07:45 UTC, kyzinatra commented on packages/client/src/pages/LoginPage/ui/LoginPage.tsx
> +        'Content-Type': 'application/json; charset=UTF-8',
Это стоит сделать хотя бы частично, иначе очень много логики повторяется, по сути копипаст. Как минимум стоит вынести типичные заголовки, обработку запроса на res.OK и res.json а также базовый URL
Остальное можете оставить, как есть, хотя я бы вынес конечно

2024-09-03 05:42 UTC, kyzinatra approved these changes
Отличная работа! Так выглядит гораздо лучше. Теперь эта система расширяема и в ней приятно разбираться

2024-09-03 05:42 UTC, kyzinatra commented on packages/client/src/shared/api/apiBase.ts
> +    credentials,
Отличная работа! Круто, что вы вынесли get и post запросы и их конфиги

2024-09-03 08:52 UTC, merged