WAI-41
DinaEll/waika_project pull request #17
Opened 2024-09-03 21:00 UTC by sergeyemelianov

### Какую задачу решаем
Создать обертку для запросов - axios

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-09-04 14:58 UTC, legeidaa requested changes

2024-09-04 14:58 UTC, legeidaa commented on packages/client/src/shared/api/apiBase.ts
>        'Content-Type': 'application/json; charset=UTF-8',
В пост запросе стоит тоже добавить обработку формдаты, как в пут. В яндексовском апи это не нужно, но может быть понадобится позже, когда будем форум писать

2024-09-04 14:58 UTC, legeidaa commented on packages/client/src/shared/api/apiBase.ts
> +  imageUpload = false,
Лучше поменять название переменной на что-то более обобщенное, типа fileUpload

2024-09-05 04:52 UTC, goodprofy requested changes
Хорошая декомпозиция которую можно улучшить, endpoints можно удалить и сразу создавать папку с endpoint: user или forum и там уже складывать методы. Находить и рефакторить будет проще чем в всей кучей в endpoints, их там скоро будет очень много.

Очень важно добавить проброс ошибки и сделать джинерик, который будет валидировать параметры и ответы.

2024-09-05 04:52 UTC, goodprofy commented on packages/client/src/shared/api/apiBase.ts
> +  return await axios(appConfig.baseUrl + url, {
Код можно упростить в 2 раза, выносом повторяющихся частей с axios в одну ф-ю.
У нас будет отправка файлов для форума в апи практикума, поэтому POST должен сейчас поддерживать formData, следующие будут работать с API, ожидая что там есть получение ошибок, formData.

2024-09-05 04:52 UTC, goodprofy commented on packages/client/src/shared/api/apiBase.ts
>      .catch(error => console.error(error))
При данном подходе мы НЕ сможем получить ошибку при использовании API.
Нужно обязательно пробросить дальше
```
 .catch(error => {
      console.error(error);  
      throw error; 
    });
    ```

2024-09-05 04:52 UTC, goodprofy commented on packages/client/src/shared/api/apiBase.ts
> +    .catch(error => console.error(error))
throw error;

2024-09-05 04:52 UTC, goodprofy commented on packages/client/src/shared/api/endpoints/changeAvatar.ts
> +export const changeAvatar = async (formData: FormData) => {
Входящие параметры и ответы должны быть типизированы

2024-09-06 05:53 UTC, goodprofy requested changes
Нужно проверить apiBase.ts, скорее всего там ошибка.

В целом очень хорошая типизация, ясно и главное удобно.

По FSD не могу сказать точно куда положить типы, мне кажется лишним их существование отдельно от API, потому что избыточно их экспортировать в проект.

2024-09-06 05:53 UTC, goodprofy commented on packages/client/src/shared/api/apiBase.ts
> +enum METHODS {
Типы в TypeScript принято писать с заглавной буквы. Это улучшает читаемость и соответствует стандартам.
Это локальная переменная. А глобальные переменные следует именовать в верхнем регистре (CAPS), чтобы сразу было понятно, что они глобальные.
В enum-ах не рекомендуется использовать окончание на "s", так как это может сбивать с толку. Название enum должно быть в единственном числе.
Для enum-ов предпочтительно использовать const enum, так как в этом случае на выходе будет непосредственное значение, а не IIFE (Immediately Invoked Function Expression), что повышает производительность.
Более подробно о работе с enum в TypeScript можно почитать [здесь](https://www.typescriptlang.org/docs/handbook/enums.html).

2024-09-06 05:53 UTC, goodprofy commented on packages/client/src/shared/api/apiBase.ts
> +type Method = typeof METHODS[keyof typeof METHODS]
Определение типа Method через typeof METHODS[keyof typeof METHODS] здесь избыточно. Поскольку в коде используется непосредственно значение из enum, можно сразу задать тип method?: METHODS. Это позволит избавиться от дополнительной абстракции и упростит проверку типов.

Также есть другой подход: можно вообще отказаться от enum и использовать строковый литерал для определения метода HTTP-запроса, например: type Method = 'get' | 'post' | 'put' | 'delete'.

В axios методы HTTP-запросов указываются в нижнем регистре, но он не чувствителен к регистру, логично оставить так как в XHR.

2024-09-06 05:53 UTC, goodprofy commented on packages/client/src/shared/interfaces/index.ts
> +export * from './UserResponse'
Вместо использования export export * from './UserResponse' и тп, у нас в проекте принято явно указывать, какие сущности мы экспортируем, например:
`export type { UserResponse } from './UserResponse'`
Такой подход делает код более предсказуемым и легче читаемым, а также упрощает поддержку и рефакторинг. Пожалуйста, приведи код в соответствие с этими правилами.

2024-09-06 05:53 UTC, goodprofy commented on packages/client/src/shared/api/apiBase.ts
Нашел такое 
 try {
        return JSON.parse(text)
      } catch (err) {
        return text
      }
      
Точно return text?

2024-09-06 09:11 UTC, DinaEll approved these changes
Вижу поправились todo, убраны не актуальные комменты, обновлены файлы, код структурирован и понятен - хорошая работа :)

2024-09-06 14:43 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +    changeAvatar('avatar', file as File).then()
странная запись. Почему бы не использовать try catch чтоб отловить ошибку?

2024-09-06 14:45 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/PasswordChangeModal/PasswordChangeModal.tsx
> +    changePassword(formData).then()
здесь тоже обернуть в try catch

2024-09-06 15:28 UTC, goodprofy approved these changes

2024-09-06 15:28 UTC, merged