WAI-19
DinaEll/waika_project pull request #4
Opened 2024-08-24 07:42 UTC by sergeyemelianov

### Какую задачу решаем
Сверстать страницу регистрации

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-08-24 09:41 UTC, KsuBurn commented on packages/client/src/pages/RegistrationPage/ui/RegistrationPage.tsx
> +        onFinish={handleSubmit}>
минор по стилю кода: обычно эту закрывающую скобку `>` выносят на следующую строку

2024-08-24 09:48 UTC, KsuBurn approved these changes

2024-08-24 10:38 UTC, goodprofy requested changes
Мне нравится твой чистый стиль. Пожалуйста удали стили, переведи на Ant - создай PageWithLogo или ModalWithLogo, сконфигурируй и передай туда форму.

2024-08-24 10:38 UTC, goodprofy commented on package.json
> +    "jest-transform-stub": "^2.0.0",
yarn install
Вот тут пояснил https://app.pachca.com/chats/12023463?message=321258387

2024-08-24 10:38 UTC, goodprofy commented on packages/client/jest.config.js
> +    '^.+\\.svg$': 'jest-transform-stub',
Можно не ставить пакет, а сделать так
`const path = require('path');

module.exports = {
  process(src, filePath) {
    if (path.extname(filePath) !== '.svg') {
      return src;
    }

    const name = `svg-${path.basename(filePath, '.svg')}`
      .split(/\W+/)
      .map((x) => `${x.charAt(0).toUpperCase()}${x.slice(1)}`)
      .join('');

    return {
      code: /* js */ `
        const React = require('react');
        function ${name}(props) {
          return React.createElement(
            'svg',
            Object.assign({}, props, {'data-file-name': ${name}.name})
          );
        }
        module.exports = ${name};
      `
    };
  }
};
`
Использовать где-то или нет, решай сам. Тут оставь пакет.

2024-08-24 10:38 UTC, goodprofy commented on packages/client/src/app/assets/themes/font-family.scss
Шрифты нужно выпилить, у нас Ant решает эту задачу. Используй его по полной.

2024-08-24 10:38 UTC, goodprofy commented on packages/client/src/app/assets/themes/styles.scss
> +  scrollbar-width: thin !important;
<img width="607" alt="image" src="https://github.com/user-attachments/assets/6d9225e7-fafd-4536-8eea-ffb8d3e9d57f">
Давай не будем модифицировать скролл или нужно решение другое или вынести отсюда в css(думаю не сработает).

2024-08-24 10:38 UTC, goodprofy commented on packages/client/src/pages/ForumPage/ui/ForumPage.module.scss
Откати этот файл, потому что он не относится к твоему заданию.

2024-08-24 10:38 UTC, goodprofy commented on packages/client/src/pages/RegistrationPage/ui/RegistrationPage.module.scss
Создай отдельный компонент, в нем используй модалку из Ant, у нее уже все стили есть.

2024-08-24 10:38 UTC, goodprofy commented on packages/client/src/widgets/Layout/ui/Layout.module.scss
Тоже нужно убрать этот файл.

2024-08-24 10:38 UTC, goodprofy commented on packages/client/tsconfig.json
Тоже нужно убрать.

2024-08-24 10:42 UTC, goodprofy commented on packages/client/src/app/assets/svg/main-logo.svg
Нужно вынести в компонент Logo

2024-08-26 04:23 UTC, DinaEll approved these changes

2024-08-26 08:07 UTC, KsuBurn commented on packages/client/src/widgets/Modal/ui/Modal.tsx
> +}
чтобы нам не мучиться и не собирать каждый раз пропсы модалки в modalProps, можно их тип указать прям в компоненте (props: ModalLayoutProps & ModalProps)
 и далее 

`<Modal {...props}>{props.children}</Modal>`

2024-08-26 08:53 UTC, goodprofy requested changes
Обязательно нужно поправить типы, чтобы с тебя брали пример.
Пожалуйста вынеси лого и заголовок в отдельный компонент ModalWithLogo.
Ребята в чате предлагали Page удалить, я поддерживаю.

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/pages/RegistrationPage/ui/RegistrationPage.tsx
> +            <Logo></Logo>
Я считаю, что его лучше вынести в отдельный компонент LogoWithModal, который будет содержать как логотип, так и заголовок. Это позволит нам унифицировать внешний вид и сделать код более структурированным.

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/pages/RegistrationPage/ui/RegistrationPage.tsx
> +          <h3 className={cls.registrationPageTitle}>Sign Up</h3>
Это <Typography.Title level={3}>Sign Up</Typography.Title> пояснил тут https://app.pachca.com/chats?thread_message_id=321231134&sidebar_message=321786096

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/shared/ui/Icon/ui/Logo.tsx
Предлагаю в этом компоненте сделать как было https://github.com/DinaEll/waika_project/blob/6e4294299519cd5138cd19db31e67127c4105ece/packages/client/src/pages/RegistrationPage/ui/RegistrationPage.tsx 
```
import MainLogo from './logo.svg'
...
 <img src={MainLogo} alt="Mahjong" className={cls.logo(содержит размеры) } />
```
Это будет лучше читаться, ну и проще менять. И если вдруг где-то будет попадать в перерендер, то это не создаст нагрузку на GP, т.е элемент в памяти не будет меняться.

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/widgets/Modal/ui/Modal.tsx
> +export interface ModalLayoutProps {
Предлагаю писать Props, потому что SOLID, правило S, оно же задает контекст, а он тут один. Если будет несколько компонентов, то писать полностью.

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/widgets/Modal/ui/Modal.tsx
> +  children: React.ReactNode
Ошибка типа. Если бегло посмотреть под капот реакта, то там такой тип, а сколько раз он менялся?
Для этого они создали тип PropsWithChildren<{}>
В данном случае запись получится такая 
```
export const ModalLayout: FC<PropsWithChildren<ModalProps>> = ({
  children,
  ...modalProps
}) => {
  return <Modal {...modalProps}>{children}</Modal>
}

```
FC нужно обязательно для вывода типа в используемых местах.

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/widgets/Modal/ui/Modal.tsx
> +}
Выше написал правильный тип

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/widgets/Page/ui/Page.tsx
> +export const Page = (props: PageProps) => {
`FC<PropsWithChildren> ` и далее как в модалке - ({children})

2024-08-26 08:53 UTC, goodprofy commented on packages/client/src/widgets/Modal/ui/Modal.tsx
> +export const ModalLayout = (props: ModalLayoutProps) => {
Название файла и переменной которая экспортируется должно совпадать.

2024-08-26 16:37 UTC, sergeyemelianov commented on packages/client/src/widgets/Page/ui/Page.tsx
> +export const Page = (props: PageProps) => {
удалил компонент, нужно тогда Layout переделать на зеленый фон и тд

2024-08-26 17:11 UTC, goodprofy commented on packages/client/src/shared/ui/Icon/ui/Logo.tsx
> +    <img src={MainLogo} alt="Mahjong" className={cls[`logo${props.size}`]} />
Обалденно!

2024-08-26 17:11 UTC, goodprofy commented on packages/client/src/shared/ui/Icon/ui/Logo.tsx
> +export const Logo = (props: Props) => {
`FC<Props>`

2024-08-26 17:24 UTC, goodprofy approved these changes
Great!

2024-08-26 17:24 UTC, merged