WAI-47: Настроить Redux и Router в SSR
DinaEll/waika_project pull request #40
Opened 2024-10-04 09:52 UTC by legeidaa

### Какую задачу решаем

После выполнения этой задачи ожидается, что Redux state будет создаваться на сервере. Также на сервере будет рендериться именно тот роут, по которому пришёл пользователь. Инициализация данных по необходимости. Авторизация по куке будет в 9 спринте. Научиться пересоздавать клиентское Redux-хранилище из серверного (initialState должен быть из стейта, который был на сервере).

2024-10-04 11:41 UTC, goodprofy approved these changes
Это просто магия 🦋🕊🦄🍭🍀

2024-10-04 14:17 UTC, sergeyemelianov approved these changes

2024-10-04 18:19 UTC, MikeDevice requested changes
Необходимо решить конфликты

2024-10-05 08:50 UTC, MikeDevice approved these changes
Всё круто! Прям по учебнику! Есть некоторые моменты, которые можно улучшить. О них отписал в комментариях, но они необязательны.

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/server/index.ts
> +    void (async () => {
ты обернул в автовызываемую функцию, чтобы async сделать?  Вроде экспресс позволяет прокидывать асинхронные функции в себя:

```diff
- app.get('*', (req, res, next) => {
+ app.get('*', async (req, res, next) => {
```

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/server/index.ts
> +createServer().catch(console.error);
красота же!

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/app/router/model/routes.tsx
> +];
**можно лучше:** не дублировать `fetchData: initPageBase`, а сделать, например объект `commonOptions`, который подмешивается во все роуты, или же сделать функцию создания роута. В общем вариантов много, как не дублировать код

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/entry-server.tsx
> +            ctx: '',
опасно так коммитить куки) так можно и базу всю удалить, если кто-то сильно захочет)). А почему контекст сейчас пустой? это временное?

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/entry-server.tsx
> +          // Если форма логина возвращает 400 ошибку, нужно сделать логаут (добавил кнопку в форму)
Про пустой контекст понял. Обычно, логин в девелоперской среде не мешает никому, потому, думаю, это лишнее. Но дело твоё, как говорится)

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/pages/GamePage/ui/GamePage.tsx
> +  usePage({ initPage: initPageBase });
**Можно лучше:** когда так приходится копипастить в каждой странице одну и ту же логику, очень легко забыть об этом при создании новой страницы, потому рекомендация:

создать `<BasePage />`, которая бы внутри содержала этот хук, а все страницы просто рисовали этот `<BasePage />`

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +                : ''
А почему первый вариант не устроил?

**можно лучше:** использовать строгое сравнение: `!==`

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/shared/api/apiBase.ts
> +  // console.log('baseRequest', url, method, headers, data);
это нужно в будущем? если нет, то лучше удалить. Если не следить за такими комментариями, то можно быстро обрасти ими

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/shared/hooks/usePage.ts
> +//packages/client/src/hooks/usePage.ts
Этот коммент нужен?

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/shared/store/ssr/ssr.slice.ts
> +// packages/client/src/slices/ssrSlice.ts
а это?

2024-10-05 08:50 UTC, MikeDevice commented on packages/client/src/shared/store/user/user.action.ts
> +      }
**можно лучше:** в будущем будет много экшонов, и в каждом писать такой сложный `try catch` будет запарно, потому лучше завести хелпер, например, `createAction` или как-то так, где внутри была бы обработка ошибок, и использовать этот хелпер в каждом экшне.

2024-10-07 06:39 UTC, legeidaa commented on packages/client/server/index.ts
> +    void (async () => {
eslint ругается на "Promise returned in function argument where a void return was expected". Кроме как с iife решить никак не смог

2024-10-07 06:41 UTC, legeidaa commented on packages/client/src/entry-server.tsx
> +            ctx: '',
Да, забыл удалить значение кук, как и кучу других комментов)) А чем могут куки навредить в этом конкретном случае, они ведь при каждом логине разные? То есть, насколько я понимаю, мои товарищи под этими же куками зайти не смогут

2024-10-07 06:42 UTC, legeidaa commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +                : ''
Тоже elint предупреждение выдавал, а я квикфиксом исправил и проглядел нестрогое равенство

2024-10-07 07:08 UTC, merged