WAI-55 - Эмодзи(клиентская часть)
DinaEll/waika_project pull request #46
Opened 2024-10-19 12:01 UTC by sergeyemelianov

### Какую задачу решаем

Проектирование и планирование:
- Определение пользовательского интерфейса для выбора и отображения эмодзи.
- Определение,как эмодз ибудут представлены в коде (например,
в виде строки с кодом эмодзи, или в виде специализированных изображений).

Реализация пользовательского интерфейса для эмодзи
- Разработка элементов интерфейса для отображения доступных для выбора эмодзи.
- Разработка элементов интерфейса для отображения эмодзи, которые были выбраны в качестве реакции на топик.

Интеграция с API
- Разработка функций для отправки запросов к API для добавления эмодзи в качестве реакции на топик.
- Разработка функций для получения информации о текущих эмодзи- реакциях на топик

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-20 06:08 UTC, goodprofy approved these changes

2024-10-21 11:11 UTC, MikeDevice requested changes
Мне очень понравилось разделение кода: что отдельно лежат типы, отдельно запросы и тд, но есть большая проблема с рассинхроном данных, о чём написал в комменте. Это надо поправить.

2024-10-23 12:34 UTC, MikeDevice approved these changes
Довольно сложненько вышло. Но не переживай, всё приходит с опытом. 

Главная рекомендация:
разносить логику по уровням приложения, чтобы компоненты не знали о том, что они рисуют. так у тебя получился хорошая архитектура, где ты сможешь менять данные, не изменяя сами компоненты

2024-10-23 12:34 UTC, MikeDevice commented on packages/client/src/widgets/ButtonReaction/ui/ButtonReaction.tsx
> +    setIsOpen(!isOpen);
```suggestion
    setIsOpen((isOpen) => !isOpen);
```

лучше так делать, потому что изменения стейта — очень мудрёная операция в реакте, и может произойти рассинхрон, когда меняешь состояние, основываясь на предыдущее значение.

Вот тут есть хорошая статья с примерами: https://habr.com/ru/companies/otus/articles/667706/

2024-10-23 12:34 UTC, MikeDevice commented on packages/client/src/widgets/ButtonReaction/ui/ButtonReaction.tsx
> +    }
сложная логика вышла. я рекомендую вынносить всегда логику работы приложения из реакта. так будет проще потом переиспользовать и логику и сам компонент, так как он не будет знать, как эта логика устроена и будет просто рисовать цифру с картинкой

2024-10-24 11:06 UTC, merged