Wai 23
DinaEll/waika_project pull request #7
Opened 2024-08-27 16:55 UTC by DinaEll

### Какую задачу решаем
Документ с описанием механик и логики игры
https://linear.app/waika/issue/WAI-23/dokument-s-opisaniem-mehanik-i-logiki-igry

2024-08-27 17:12 UTC, legeidaa commented on docs/scenario.md
> +Цель игры набрать как можно больше очков, очки набираются за скорость прохождения игры.
Мы с Юрой согласились, что лучше сделать целью очищение поля за как можно меньшее время, а то переводить время в какие-то очки странно

2024-08-27 17:12 UTC, legeidaa commented on docs/scenario.md
> +Система отображает главное меню игры.
Мы из главного меню переходим на отдельную страницу старта, где будут правила, а уже оттуда идет переход к игре

2024-08-27 17:12 UTC, legeidaa commented on docs/scenario.md
> +Старт игры
Это кнопки на экране самой игры? Если да, то старт наверное лишняя

2024-08-28 06:02 UTC, goodprofy requested changes
Отличное ТЗ

2024-08-28 06:02 UTC, goodprofy commented on docs/scenario.md
> +Старт игры
В самой игре будет таймер, 3,2,1 goooooo!!!! А на старте будет старт)

2024-08-28 06:02 UTC, goodprofy commented on docs/scenario.md
> +Старт игры
Я пока так думаю, но есть какое-то сопротивление, все еще кажется что это часть игры

2024-08-28 08:42 UTC, DinaEll commented on docs/scenario.md
> +Цель игры набрать как можно больше очков, очки набираются за скорость прохождения игры.
Поправила Цель игры - соединить плитки за наименьшее время.

2024-08-28 08:43 UTC, DinaEll commented on docs/scenario.md
> +Система отображает главное меню игры.
Поправила
"Из главного меню игрок переходит на страницу старта игры, где будет описание правил и функция (кнопка) старта игры."

2024-08-28 08:44 UTC, DinaEll commented on docs/scenario.md
> +Старт игры
Предлагаю пока не трогать эту формулировку, поправим по ходу работы. Но заметка стоящая

2024-08-28 08:45 UTC, DinaEll commented on docs/scenario.md
> +#### Технические требования User Story:
Поправила

2024-08-28 08:46 UTC, DinaEll commented on docs/scenario.md
> +Игрок может выбрать, начать новую партию или выйти в главное меню.
Давай "главное меню" оставим пока. Посмотрим как игра будет развиваться, через еще спринт поменяем формулировку. Пока у нас это "главное меню" технически есть - страничка со страничками

2024-08-28 08:46 UTC, DinaEll commented on docs/scenario.md
> +Система сохраняет прогресс и результаты игрока.
Не, все четко заметил, тут надо поправить. Убрала про прогресс

2024-08-28 09:17 UTC, goodprofy approved these changes
Класс!

2024-08-28 10:21 UTC, legeidaa approved these changes

2024-08-28 15:34 UTC, merged