Верстка экрана завершения игры
DinaEll/waika_project pull request #8
Opened 2024-08-27 17:34 UTC by DinaEll

### Какую задачу решаем
Сверстать экран завершения игры
К описанию задачи прикрепила скриншот, как выглядит визуально результат
https://linear.app/waika/issue/WAI-24/sverstat-ekran-zaversheniya-igry

2024-08-27 21:10 UTC, sergeyemelianov commented on packages/client/src/pages/GameResultsPage/ui/GameResultsPage.tsx
> +        <Form className={cls.gameOverPageWrapper} layout="vertical">
В этом компоненте использовать Form и Form.Item не нужно, они для других целей.
У ant можно позаимствовать что-то типа Space, как пример.

2024-08-27 21:12 UTC, sergeyemelianov commented on packages/client/src/pages/GameResultsPage/ui/GameResultsPage.tsx
>    test?: string
это можно удалить

2024-08-27 21:15 UTC, sergeyemelianov commented on packages/client/src/pages/GameResultsPage/ui/GameResultsPage.tsx
> +      <LogoWithModal
в PR Юры будет правка LogoWithModal, тут эти пропсы уже не понадобятся (кроме title)

2024-08-28 06:11 UTC, goodprofy requested changes
Молодец, экран я этот не делал, но все так, как обсуждали.
Думаю можно баллы уже заменить на время в игре.
С предложениями Сергея согласен, не забудь почистить стили. 
Могу рекомендовать этот модуль https://ant.design/components/result
Из LogoWithModal пропсы сейчас не убирай, потому что окно не будет работать. Мы это уберем в техдолг и закроем его в конце спринта или в начале следующего вместе с внедрением соглашений.

2024-08-28 15:46 UTC, DinaEll commented on packages/client/src/pages/GameResultsPage/ui/GameResultsPage.tsx
>    test?: string
Оки, удалила

2024-08-28 15:56 UTC, DinaEll commented on packages/client/src/pages/GameResultsPage/ui/GameResultsPage.tsx
> +        <Form className={cls.gameOverPageWrapper} layout="vertical">
Я с ant еще не сильно подружилась, поэтому для упрощения использую стандартные div and label

2024-08-28 15:57 UTC, DinaEll commented on packages/client/src/pages/GameResultsPage/ui/GameResultsPage.tsx
> +      <LogoWithModal
Пока LogoWithModal решили оставить, обновим в след спринте

2024-08-28 16:25 UTC, goodprofy approved these changes

2024-08-28 16:44 UTC, sergeyemelianov approved these changes

2024-08-29 08:38 UTC, merged