WAI-22
DinaEll/waika_project pull request #9
Opened 2024-08-28 16:17 UTC by KsuBurn

### Какую задачу решаем

https://linear.app/waika/issue/WAI-22/sverstat-stranicu-polzovatelya

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-08-28 16:21 UTC, DinaEll approved these changes
Все аккуратно, красиво, todo есть, но все по делу
К Form.Item в моем коде Сергей оставлял замечания, возможно тебе тоже нужно их переделать, но я не уверена, лучше переспросить у него
С моей стороны остальное оки

2024-08-28 17:03 UTC, goodprofy requested changes

2024-08-28 17:03 UTC, goodprofy commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +      <Modal
Дублирование кода который есть в LogoWithModal
Пример: https://github.com/DinaEll/waika_project/blob/WAI-22/packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
Можно допилить под свои нужды. Пока не переименовывать.

2024-08-28 17:40 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +      <Modal
поправила

2024-08-28 19:42 UTC, sergeyemelianov approved these changes
Некритичные замечания, исправления на свое усмотрение. Код выглядит хорошо!

2024-08-28 19:42 UTC, sergeyemelianov commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +    console.log('handlePreview', file)
нужен?

2024-08-28 19:42 UTC, sergeyemelianov commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +    fetch('https://ya-praktikum.tech/api/v2/user/profile/avatar', {
baseURL можно вынести в конфиг уже на этом этапе

2024-08-29 04:15 UTC, goodprofy commented on packages/client/package.json
> +    "@ant-design/icons": "^5.4.0",
Молодец что установила, я не стал это делать, увидел пакет в зависимостях antd, но не проверил импорт из основного пакета. Оказывается начиная с 4 версии они пытаются его выпилить.

2024-08-29 06:02 UTC, goodprofy requested changes
В целом ок! Но нужно разобраться с импортом из Antd.

2024-08-29 13:48 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +    console.log('handlePreview', file)
улдалила

2024-08-29 13:50 UTC, KsuBurn commented on packages/client/src/app/providers/router/model/router.tsx
> +import { Layout } from '@/widgets/Layout'
я уже не помню, что я тут делала, в этом нет ничего критичного

2024-08-29 13:57 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +export const AvatarChangeModal = ({ ...props }: ModalProps) => {
я в курсе, спасибо
но ранее ребята делали так, поэтому я не стала отходить от общего стиля

2024-08-29 14:01 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.module.scss
> +    padding: 32px 0 !important;
поправила на марджин, он тут логичнее будет

2024-08-29 14:04 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +import Title from 'antd/lib/typography/Title'
убрала вообще так как ты ниже написал, что в модалке и так h5

2024-08-29 14:08 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +import { PasswordChangeModal } from '@/pages/ProfilePage/ui/PasswordChangeModal/PasswordChangeModal'
Чтооо? по фсд надо еще импорты писать по особому?((

Вообще мне вебшторм сам прописывает импорты, а не я руками их пишу) и конечно постоянно за этим следить такое себе =/

2024-08-29 14:11 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +  const getBase64 = (file: RcFile) =>
RcFile я брала из библиотеки прям
![image](https://github.com/user-attachments/assets/3d3d59e9-b5f8-4164-9dff-3fa39a1eb197)

2024-08-29 14:23 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +      title={<Title level={5}>Change Avatar</Title>}
done

2024-08-29 14:25 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +import { RcFile } from 'antd/es/upload/interface'
спасибо, поправила. С ант не знакома, поэтому пока непонятна документация, где и что смотреть)

2024-08-30 04:28 UTC, goodprofy commented on packages/client/src/app/providers/router/model/router.tsx
> +import { Layout } from '@/widgets/Layout'
Речь не про критичность, а про чистоту в PR.

2024-08-30 04:31 UTC, goodprofy commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +export const AvatarChangeModal = ({ ...props }: ModalProps) => {
И я их тоже поправлял, тебе стоило их поправить)

2024-08-30 04:36 UTC, goodprofy commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +import { PasswordChangeModal } from '@/pages/ProfilePage/ui/PasswordChangeModal/PasswordChangeModal'
Ну раз это у всех разруливается автоматом, кроме меня, то пусть будет так)
Я тоже не хочу в это вникать. У меня тут разруливает автоматом, а где надо через @ не разруливает(

2024-08-30 04:45 UTC, goodprofy approved these changes

2024-08-30 05:57 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +export const AvatarChangeModal = ({ ...props }: ModalProps) => {
Я и поправила

2024-08-30 07:49 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/PasswordChangeModal/PasswordChangeModal.tsx
> +  const handleChange = (e: ChangeEvent<HTMLInputElement>): void => {
считаю void никогда не бывает лишним
тут просто желательно придерживаться одного стиля конечно

2024-08-30 08:17 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/ProfilePage.tsx
> +          <Avatar
использовала UserAvatar

2024-08-30 08:22 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +  const UploadButton = () => (
убрала

2024-08-30 08:22 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +      style={{
убрала

2024-08-30 08:23 UTC, KsuBurn commented on packages/client/src/pages/ProfilePage/ui/PasswordChangeModal/PasswordChangeModal.tsx
> +export const PasswordChangeModal = ({ ...props }: ModalProps) => {
исправлено

2024-08-30 11:02 UTC, kyzinatra commented
К сожалению у нас нет доступа к linear и я не смогу посмотреть задачу. Прошу описывать задачу и что было сделано в pull request. Так я смогу точнее погрузится вашу работу. Как только опишите пришлите работу снова и я ее проверю как можно скорее

2024-08-30 14:51 UTC, kyzinatra commented on packages/client/src/pages/ProfilePage/ui/AvatarChangeModal/AvatarChangeModal.tsx
> +    new Promise((resolve, reject) => {
Такую функцию мне кажется стоит вынести в utils

2024-08-30 14:53 UTC, kyzinatra commented on packages/client/src/shared/ui/UserAvatar/UserAvatar.tsx
> +      icon={<UserOutlined />}
Обычно используют вместо `classnames` просто `clsx` или `cn`, так короче

2024-08-30 14:55 UTC, kyzinatra commented
Отличная работа! Хорошая верстка и подключение api. Отдельно отмечу отличное ревью ваших коллег. Вопросов по работе у меня нет, так что принимаю ее и желаю вам успехов в дальнейшем обучении

2024-08-30 17:39 UTC, legeidaa approved these changes

2024-09-01 07:02 UTC, merged